version: '3'

services:
  app:
    build: .
    command: 'npm run dev:server'
    volumes:
      - .:/usr/app
    ports:
      - '3333:3333'
    networks:
      - moneyshield

networks:
  moneyshield:
    driver: bridge
